package com.bjpowernode.crm.settings.domain;

import lombok.Data;

@Data
public class DicValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_value.id
     *
     * @mbggenerated Tue Nov 03 17:09:33 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_value.value
     *
     * @mbggenerated Tue Nov 03 17:09:33 CST 2020
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_value.text
     *
     * @mbggenerated Tue Nov 03 17:09:33 CST 2020
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_value.order_no
     *
     * @mbggenerated Tue Nov 03 17:09:33 CST 2020
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_value.type_code
     *
     * @mbggenerated Tue Nov 03 17:09:33 CST 2020
     */
    private String typeCode;
}